import { Asset, AssetLifecycle, PrismaClient, ProductionAssetKind } from "@prisma/client";
import { LayerPlan } from "./visualCompositionPlanner";

export type ReuseDecision = "REUSE" | "MODIFY" | "GENERATE";

/** What GENERATE_LAYER_ASSET needs to (re)produce an asset; stored on Asset.metadata.request. */
export interface LayerGenRequest {
  role: LayerPlan["assetRole"];
  prompt: string;
  negativePrompt: string;
  width: number;
  height: number;
  seed: number;
  style: string;
  transparent: boolean;
  painterHint: Record<string, unknown>;
  /** Identity references for MODIFY (e.g. the character's existing master image). */
  references?: { kind: "character" | "location" | "style"; assetId: string; storageKey: string }[];
}

const USABLE: AssetLifecycle[] = ["READY", "APPROVED"];
const IN_FLIGHT: AssetLifecycle[] = ["REQUIRED", "GENERATING"];
const TIERS = ["S", "M", "L"] as const;

function hashKey(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) h = Math.imul(h ^ s.charCodeAt(i), 16777619);
  return h >>> 0;
}

/** Deterministic seed per reuse key (same asset → same seed → reproducible). */
export function seedFor(reuseKey: string, base = 0): number {
  return (hashKey(reuseKey) ^ base) & 0x7fffffff;
}

/**
 * Asset reuse key for a layer. Procedural character rigs cover every pose and
 * expression at runtime, so one rig per character and size tier is enough;
 * single-image characters from an image model need one image per pose and
 * expression (the identity is kept by passing the master image as reference).
 */
export function effectiveReuseKey(layer: LayerPlan, imageProvider: string): string {
  if (layer.assetRole === "character" && imageProvider !== "procedural") return `${layer.reuseKey}:${layer.pose ?? "standing"}:${layer.expression ?? "neutral"}`;
  return layer.reuseKey;
}

function kindFor(layer: LayerPlan, imageProvider: string): ProductionAssetKind {
  return layer.assetRole === "character" && imageProvider === "procedural" ? "RIG" : "IMAGE";
}

export interface ResolvedLayerAsset {
  asset: Asset;
  decision: ReuseDecision;
  /** True when the caller must queue generation for `asset`. */
  needsGeneration: boolean;
  /** True while the asset is being generated by another job. */
  pending: boolean;
}

export interface ResolveContext {
  storyId: string;
  imageProvider: string; // provider of the image model that would generate (procedural | comfyui | http-inference)
  /** Production renders may only reuse assets whose generating model is licence-cleared. */
  isVersionUsable?: (asset: Asset) => Promise<boolean>;
  seedBase: number;
  style: string;
  refs: { characterRefId?: string; locationRefId?: string; propRefId?: string };
}

/**
 * AssetLibrary: REUSE ▸ MODIFY ▸ GENERATE.
 *  - REUSE an equivalent ready asset (same reuse key; for rigs, any equal or
 *    larger size tier of the same character).
 *  - MODIFY: a new pose/expression of a character that already has a master
 *    image — generated with that image as identity reference.
 *  - GENERATE otherwise.
 * Assets currently being generated are shared, never duplicated.
 */
export async function resolveLayerAsset(db: PrismaClient, layer: LayerPlan, ctx: ResolveContext): Promise<ResolvedLayerAsset> {
  const key = effectiveReuseKey(layer, ctx.imageProvider);
  const candidates = await db.asset.findMany({ where: { reuseKey: key, status: { in: [...USABLE, ...IN_FLIGHT] } }, orderBy: [{ status: "asc" }, { updatedAt: "desc" }] });
  for (const a of candidates) {
    if (USABLE.includes(a.status) && (!ctx.isVersionUsable || (await ctx.isVersionUsable(a)))) return { asset: a, decision: "REUSE", needsGeneration: false, pending: false };
  }
  const inFlight = candidates.find((a) => IN_FLIGHT.includes(a.status));
  if (inFlight) return { asset: inFlight, decision: "REUSE", needsGeneration: false, pending: true };

  // Rigs: a larger tier of the same character scales down cleanly.
  if (layer.assetRole === "character" && ctx.imageProvider === "procedural") {
    const tier = key.slice(-1) as (typeof TIERS)[number];
    const bigger = TIERS.slice(TIERS.indexOf(tier) + 1).map((t) => key.slice(0, -1) + t);
    if (bigger.length) {
      const big = await db.asset.findFirst({ where: { reuseKey: { in: bigger }, status: { in: USABLE } }, orderBy: { updatedAt: "desc" } });
      if (big && (!ctx.isVersionUsable || (await ctx.isVersionUsable(big)))) return { asset: big, decision: "REUSE", needsGeneration: false, pending: false };
    }
  }

  let decision: ReuseDecision = "GENERATE";
  const references: NonNullable<LayerGenRequest["references"]> = [];
  if (layer.assetRole === "character" && ctx.imageProvider !== "procedural") {
    const master = await db.asset.findFirst({ where: { reuseKey: { startsWith: `${layer.reuseKey}:` }, status: { in: USABLE }, storageKey: { not: null } }, orderBy: { updatedAt: "desc" } });
    if (master?.storageKey) {
      decision = "MODIFY";
      references.push({ kind: "character", assetId: master.id, storageKey: master.storageKey });
    }
  }
  const request: LayerGenRequest = {
    role: layer.assetRole,
    prompt: layer.prompt,
    negativePrompt: layer.negativePrompt,
    width: layer.pixelSize.width,
    height: layer.pixelSize.height,
    seed: seedFor(key, ctx.seedBase),
    style: ctx.style,
    transparent: layer.assetRole !== "background",
    painterHint: layer.painterHint,
    references: references.length ? references : undefined,
  };
  const asset = await db.asset.create({
    data: {
      kind: kindFor(layer, ctx.imageProvider),
      role: layer.assetRole,
      name: layer.name,
      reuseKey: key,
      // story-scoped characters are cleaned up with their story; locations/props are a shared library
      storyId: key.includes(`story:${ctx.storyId}:`) ? ctx.storyId : null,
      status: "REQUIRED",
      characterRefId: ctx.refs.characterRefId,
      locationRefId: ctx.refs.locationRefId,
      propRefId: ctx.refs.propRefId,
      metadata: { request } as never,
    },
  });
  return { asset, decision, needsGeneration: true, pending: false };
}

/** The depth map derived from an image asset's current version, if any. */
export async function depthFor(db: PrismaClient, asset: Asset): Promise<Asset | null> {
  return db.asset.findFirst({ where: { sourceAssetId: asset.id, kind: "DEPTH", status: { in: USABLE } }, orderBy: { updatedAt: "desc" } });
}

/** True when an asset is placeholder art an administrator has not accepted. */
export function isUnresolvedPlaceholder(a: Pick<Asset, "isPlaceholder" | "status">): boolean {
  return a.isPlaceholder && a.status !== "APPROVED";
}
