import { AiTask } from "@prisma/client";

export interface DefaultModel {
  modelId: string;
  name: string;
  provider: "procedural" | "comfyui" | "http-inference";
  task: AiTask;
  version: string;
  workflow?: string;
  license: string;
  licenseUrl?: string;
  /** Set only when the licence was checked against the publisher's own page (date of the check). */
  licenseVerifiedAt?: string;
  licenseNotes: string;
  commercialUseAllowed: boolean;
  productionApproved: boolean;
  attributionRequired: boolean;
  attributionText?: string;
  redistributionNotes?: string;
  localOnly: boolean;
  gpuRequirement?: string;
  recommendedVramGb: number;
  qualityScore: number;
  speedScore: number;
  enabled: boolean;
  isDefault: boolean;
  config?: Record<string, unknown>;
}

// Licence facts below were checked on 2026-10-05 against the publishers'
// GitHub repositories (Hugging Face was not reachable from the build
// environment). Anything not verified that day has licenseVerifiedAt unset
// and productionApproved = false. Re-verify before every deployment:
// licences change, and model cards can add terms the repository does not.
const VERIFIED = "2026-10-05";

export const DEFAULT_MODELS: DefaultModel[] = [
  // ---- Built-in (our own code; no third-party weights) ----
  {
    modelId: "atma-procedural-v1",
    name: "Atma procedural graphic-novel painter",
    provider: "procedural",
    task: "IMAGE_GENERATION",
    version: "1.0.0",
    license: "Proprietary (this codebase)",
    licenseNotes: "Built-in vector painter. Output is placeholder art: an editor must approve each asset before it can be published.",
    commercialUseAllowed: true,
    productionApproved: true,
    attributionRequired: false,
    localOnly: true,
    recommendedVramGb: 0,
    qualityScore: 30,
    speedScore: 95,
    enabled: true,
    isDefault: true,
  },
  {
    modelId: "atma-alpha-matte-v1",
    name: "Atma alpha-channel matte",
    provider: "procedural",
    task: "SEGMENTATION",
    version: "1.0.0",
    license: "Proprietary (this codebase)",
    licenseNotes: "Derives masks from an image's alpha channel; cannot cut out subjects from opaque images.",
    commercialUseAllowed: true,
    productionApproved: true,
    attributionRequired: false,
    localOnly: true,
    recommendedVramGb: 0,
    qualityScore: 40,
    speedScore: 99,
    enabled: true,
    isDefault: true,
  },
  {
    modelId: "atma-layer-depth-v1",
    name: "Atma layer depth",
    provider: "procedural",
    task: "DEPTH",
    version: "1.0.0",
    license: "Proprietary (this codebase)",
    licenseNotes: "Builds depth maps from layer Z order plus a ground-plane gradient for backgrounds.",
    commercialUseAllowed: true,
    productionApproved: true,
    attributionRequired: false,
    localOnly: true,
    recommendedVramGb: 0,
    qualityScore: 40,
    speedScore: 99,
    enabled: true,
    isDefault: true,
  },
  {
    modelId: "atma-diffusion-fill-v1",
    name: "Atma diffusion fill",
    provider: "procedural",
    task: "INPAINTING",
    version: "1.0.0",
    license: "Proprietary (this codebase)",
    licenseNotes: "Fills masked regions by iterative neighbour averaging (removes small objects/edge halos).",
    commercialUseAllowed: true,
    productionApproved: true,
    attributionRequired: false,
    localOnly: true,
    recommendedVramGb: 0,
    qualityScore: 25,
    speedScore: 90,
    enabled: true,
    isDefault: true,
  },

  // ---- Image generation (self-hosted) ----
  {
    modelId: "flux1-schnell",
    name: "FLUX.1 [schnell]",
    provider: "comfyui",
    task: "IMAGE_GENERATION",
    version: "1.0",
    workflow: "flux-schnell-txt2img.json",
    license: "Apache-2.0",
    licenseUrl: "https://github.com/black-forest-labs/flux",
    licenseVerifiedAt: VERIFIED,
    licenseNotes: "Repository licence table lists FLUX.1 [schnell] as apache-2.0 (FLUX.1 [dev] is non-commercial).",
    commercialUseAllowed: true,
    productionApproved: true,
    attributionRequired: true,
    attributionText: "FLUX.1 [schnell] by Black Forest Labs (Apache-2.0)",
    redistributionNotes: "Apache-2.0: keep licence and NOTICE when redistributing weights.",
    localOnly: true,
    gpuRequirement: "NVIDIA, CUDA 12; fp8 checkpoint",
    recommendedVramGb: 16,
    qualityScore: 80,
    speedScore: 75,
    enabled: false,
    isDefault: false,
    config: { steps: 4, cfg: 1.0, sampler: "euler", scheduler: "simple", checkpoint: "flux1-schnell-fp8.safetensors" },
  },
  {
    modelId: "qwen-image",
    name: "Qwen-Image",
    provider: "http-inference",
    task: "IMAGE_GENERATION",
    version: "1.0",
    license: "Apache-2.0",
    licenseUrl: "https://github.com/QwenLM/Qwen-Image",
    licenseVerifiedAt: VERIFIED,
    licenseNotes: "Repository states: Qwen-Image is licensed under Apache 2.0.",
    commercialUseAllowed: true,
    productionApproved: true,
    attributionRequired: true,
    attributionText: "Qwen-Image by Alibaba Qwen team (Apache-2.0)",
    localOnly: true,
    gpuRequirement: "NVIDIA, ≥ 40 GB VRAM in bf16 (less with quantisation/offload)",
    recommendedVramGb: 40,
    qualityScore: 88,
    speedScore: 40,
    enabled: false,
    isDefault: false,
    config: { steps: 30, guidance: 4.0 },
  },
  {
    modelId: "sdxl-base-1.0",
    name: "Stable Diffusion XL 1.0 base",
    provider: "comfyui",
    task: "IMAGE_GENERATION",
    version: "1.0",
    workflow: "sdxl-txt2img.json",
    license: "CreativeML Open RAIL++-M",
    licenseUrl: "https://github.com/Stability-AI/generative-models/blob/main/model_licenses/LICENSE-SDXL1.0",
    licenseVerifiedAt: VERIFIED,
    licenseNotes: "Grant permits commercial use and SaaS hosting, but Attachment A use-based restrictions apply. Needs legal sign-off for news use before production approval.",
    commercialUseAllowed: true,
    productionApproved: false,
    attributionRequired: true,
    attributionText: "Stable Diffusion XL 1.0 (CreativeML Open RAIL++-M)",
    redistributionNotes: "Derivatives must carry the same use-based restrictions.",
    localOnly: true,
    gpuRequirement: "NVIDIA, ≥ 10 GB",
    recommendedVramGb: 10,
    qualityScore: 70,
    speedScore: 60,
    enabled: false,
    isDefault: false,
    config: { steps: 30, cfg: 6.0, sampler: "dpmpp_2m", scheduler: "karras", checkpoint: "sd_xl_base_1.0.safetensors" },
  },
  {
    modelId: "flux1-dev",
    name: "FLUX.1 [dev]",
    provider: "comfyui",
    task: "IMAGE_GENERATION",
    version: "1.0",
    license: "FLUX.1-dev Non-Commercial License",
    licenseUrl: "https://github.com/black-forest-labs/flux",
    licenseVerifiedAt: VERIFIED,
    licenseNotes: "Non-commercial. Requires a separate commercial licence from Black Forest Labs.",
    commercialUseAllowed: false,
    productionApproved: false,
    attributionRequired: true,
    localOnly: true,
    recommendedVramGb: 24,
    qualityScore: 90,
    speedScore: 35,
    enabled: false,
    isDefault: false,
  },

  // ---- Segmentation ----
  {
    modelId: "birefnet",
    name: "BiRefNet (dichotomous segmentation / background removal)",
    provider: "http-inference",
    task: "SEGMENTATION",
    version: "1.0",
    license: "MIT",
    licenseUrl: "https://github.com/ZhengPeng7/BiRefNet",
    licenseVerifiedAt: VERIFIED,
    licenseNotes: "Repository is MIT licensed.",
    commercialUseAllowed: true,
    productionApproved: true,
    attributionRequired: true,
    attributionText: "BiRefNet (MIT)",
    localOnly: true,
    recommendedVramGb: 4,
    qualityScore: 85,
    speedScore: 70,
    enabled: false,
    isDefault: false,
  },
  {
    modelId: "sam2.1-hiera-large",
    name: "Segment Anything 2.1 (Hiera-L)",
    provider: "http-inference",
    task: "SEGMENTATION",
    version: "2.1",
    license: "Apache-2.0",
    licenseUrl: "https://github.com/facebookresearch/sam2",
    licenseVerifiedAt: VERIFIED,
    licenseNotes: "Checkpoints, demo and training code are Apache 2.0 (demo fonts under SIL OFL 1.1).",
    commercialUseAllowed: true,
    productionApproved: true,
    attributionRequired: true,
    attributionText: "SAM 2 by Meta (Apache-2.0)",
    localOnly: true,
    recommendedVramGb: 6,
    qualityScore: 85,
    speedScore: 60,
    enabled: false,
    isDefault: false,
  },
  {
    modelId: "rmbg-2.0",
    name: "BRIA RMBG 2.0",
    provider: "http-inference",
    task: "SEGMENTATION",
    version: "2.0",
    license: "CC BY-NC 4.0 (not verified in this session)",
    licenseNotes: "Believed non-commercial without a BRIA commercial agreement. Not verified — do not enable for production.",
    commercialUseAllowed: false,
    productionApproved: false,
    attributionRequired: true,
    localOnly: true,
    recommendedVramGb: 4,
    qualityScore: 88,
    speedScore: 70,
    enabled: false,
    isDefault: false,
  },

  // ---- Depth ----
  {
    modelId: "depth-anything-v2-small",
    name: "Depth Anything V2 Small",
    provider: "http-inference",
    task: "DEPTH",
    version: "2.0",
    workflow: "depth-anything-v2-small.json", // used if an admin switches the provider to comfyui
    license: "Apache-2.0",
    licenseUrl: "https://github.com/DepthAnything/Depth-Anything-V2",
    licenseVerifiedAt: VERIFIED,
    licenseNotes: "Small is Apache-2.0. Base/Large/Giant are CC-BY-NC-4.0 (non-commercial).",
    commercialUseAllowed: true,
    productionApproved: true,
    attributionRequired: true,
    attributionText: "Depth Anything V2 Small (Apache-2.0)",
    localOnly: true,
    recommendedVramGb: 2,
    qualityScore: 75,
    speedScore: 90,
    enabled: false,
    isDefault: false,
  },
  {
    modelId: "depth-anything-v2-large",
    name: "Depth Anything V2 Large",
    provider: "http-inference",
    task: "DEPTH",
    version: "2.0",
    license: "CC-BY-NC-4.0",
    licenseUrl: "https://github.com/DepthAnything/Depth-Anything-V2",
    licenseVerifiedAt: VERIFIED,
    licenseNotes: "Non-commercial.",
    commercialUseAllowed: false,
    productionApproved: false,
    attributionRequired: true,
    localOnly: true,
    recommendedVramGb: 4,
    qualityScore: 90,
    speedScore: 60,
    enabled: false,
    isDefault: false,
  },
  {
    modelId: "midas-dpt-hybrid",
    name: "MiDaS DPT-Hybrid",
    provider: "http-inference",
    task: "DEPTH",
    version: "3.0",
    license: "MIT",
    licenseUrl: "https://github.com/isl-org/MiDaS",
    licenseVerifiedAt: VERIFIED,
    licenseNotes: "Code and weights released under MIT.",
    commercialUseAllowed: true,
    productionApproved: true,
    attributionRequired: true,
    attributionText: "MiDaS (MIT)",
    localOnly: true,
    recommendedVramGb: 2,
    qualityScore: 65,
    speedScore: 85,
    enabled: false,
    isDefault: false,
  },

  // ---- Inpainting ----
  {
    modelId: "big-lama",
    name: "LaMa (big-lama)",
    provider: "http-inference",
    task: "INPAINTING",
    version: "1.0",
    license: "Apache-2.0",
    licenseUrl: "https://github.com/advimman/lama/blob/main/LICENSE",
    licenseVerifiedAt: VERIFIED,
    licenseNotes: "Repository LICENSE is Apache 2.0.",
    commercialUseAllowed: true,
    productionApproved: true,
    attributionRequired: true,
    attributionText: "LaMa (Apache-2.0)",
    localOnly: true,
    recommendedVramGb: 4,
    qualityScore: 75,
    speedScore: 80,
    enabled: false,
    isDefault: false,
  },

  // ---- Upscale (registry only: the pipeline has no upscale stage yet) ----
  {
    modelId: "real-esrgan-x4plus",
    name: "Real-ESRGAN x4plus",
    provider: "http-inference",
    task: "UPSCALE",
    version: "0.3",
    license: "BSD-3-Clause",
    licenseUrl: "https://github.com/xinntao/Real-ESRGAN",
    licenseVerifiedAt: VERIFIED,
    licenseNotes: "Registry entry only — no upscale stage is wired into the pipeline yet.",
    commercialUseAllowed: true,
    productionApproved: true,
    attributionRequired: true,
    localOnly: true,
    recommendedVramGb: 2,
    qualityScore: 70,
    speedScore: 80,
    enabled: false,
    isDefault: false,
  },

  // ---- Image-to-video (optional) ----
  {
    modelId: "wan2.1-i2v-14b-480p",
    name: "Wan 2.1 I2V 14B (480p)",
    provider: "comfyui",
    task: "VIDEO_GENERATION",
    version: "2.1",
    workflow: "wan21-i2v-480p.json",
    license: "Apache-2.0",
    licenseUrl: "https://github.com/Wan-Video/Wan2.1",
    licenseVerifiedAt: VERIFIED,
    licenseNotes: "Models licensed Apache 2.0; the licence text adds content restrictions (no unlawful, harmful or misleading content).",
    commercialUseAllowed: true,
    productionApproved: true,
    attributionRequired: true,
    attributionText: "Wan 2.1 by Alibaba Wan team (Apache-2.0)",
    localOnly: true,
    gpuRequirement: "NVIDIA; fp8 weights in ComfyUI (≈24 GB class GPU; more for bf16)",
    recommendedVramGb: 24,
    qualityScore: 80,
    speedScore: 20,
    enabled: false,
    isDefault: false,
    config: {
      steps: 30,
      cfg: 5.0,
      fps: 16,
      maxPixels: 480 * 832,
      unet: "wan2.1_i2v_480p_14B_fp8_e4m3fn.safetensors",
      text_encoder: "umt5_xxl_fp8_e4m3fn_scaled.safetensors",
      vae: "wan_2.1_vae.safetensors",
      clip_vision: "clip_vision_h.safetensors",
    },
  },
  {
    modelId: "stable-video-diffusion-xt",
    name: "Stable Video Diffusion XT",
    provider: "comfyui",
    task: "VIDEO_GENERATION",
    version: "1.1",
    license: "Unverified (research release / Stability Community License)",
    licenseNotes: "Licence terms for commercial use not verified in this session. Keep disabled until legal review.",
    commercialUseAllowed: false,
    productionApproved: false,
    attributionRequired: true,
    localOnly: true,
    recommendedVramGb: 20,
    qualityScore: 60,
    speedScore: 40,
    enabled: false,
    isDefault: false,
  },
];
