import request from 'supertest';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { auth, adminToken, scopeIds, setupTestApp, userToken } from './helpers.js';

// The end-to-end path from the spec:
// ADMIN → generate 20 → validate → approve → publish → generate mock test →
// retrieve through the public API → submit → server-calculated result.
describe('complete question pipeline', () => {
  let ctx: Awaited<ReturnType<typeof setupTestApp>>;
  let admin: string;
  let ids: Awaited<ReturnType<typeof scopeIds>>;

  beforeAll(async () => {
    ctx = await setupTestApp();
    admin = await adminToken(ctx.app, ctx.db);
    ids = await scopeIds(ctx.app, admin);
  });
  afterAll(async () => ctx.close());

  let jobId: string;
  let mockTestId: string;

  it('creates a batched generation job', async () => {
    const res = await request(ctx.app)
      .post('/api/admin/generation-jobs')
      .set(auth(admin))
      .send({
        examId: ids.examId,
        subjectId: ids.mathsId,
        chapterId: ids.percentageId,
        language: 'hi',
        questionCount: 20,
        questionType: 'mcq',
        difficulty: { easy: 30, medium: 50, hard: 20 },
        explanationRequired: true,
      });
    expect(res.status).toBe(201);
    expect(res.body.status).toBe('queued');
    expect(res.body.batches).toHaveLength(1);
    expect(res.body.batches[0].difficultyMix).toEqual({ easy: 6, medium: 10, hard: 4 });
    jobId = res.body.id;
  });

  it('generates, validates and AI-reviews the batch', async () => {
    expect(await ctx.worker.drain()).toBe(1);
    const res = await request(ctx.app).get(`/api/admin/generation-jobs/${jobId}`).set(auth(admin));
    expect(res.body.status).toBe('completed');
    expect(res.body.progress).toMatchObject({ generated: 20, requested: 20, percent: 100 });
    expect(res.body.approvedCount + res.body.needsReviewCount + res.body.rejectedCount).toBe(20);
    // Nothing generated by AI is ever published automatically.
    expect(res.body.currentStatusCounts.published ?? 0).toBe(0);
  });

  it('shows questions with validation and AI review details', async () => {
    const list = await request(ctx.app).get(`/api/admin/questions?jobId=${jobId}&pageSize=50`).set(auth(admin));
    expect(list.body.total).toBe(20);
    const detail = await request(ctx.app).get(`/api/admin/questions/${list.body.items[0].id}`).set(auth(admin));
    expect(detail.body.options).toHaveLength(4);
    expect(detail.body.examName).toBe('UP Police Constable');
    expect(detail.body.chapterName).toBe('Percentage');
    expect(detail.body.reviews.map((r: { reviewerType: string }) => r.reviewerType).sort()).toEqual(['ai', 'validator']);
  });

  it('approves the questions waiting for review, then publishes', async () => {
    const pending = await request(ctx.app).get(`/api/admin/questions?jobId=${jobId}&status=needs_review`).set(auth(admin));
    for (const q of pending.body.items) {
      const r = await request(ctx.app).post(`/api/admin/questions/${q.id}/approve`).set(auth(admin)).send({ notes: 'Checked by hand' });
      expect(r.status).toBe(200);
    }
    const approved = await request(ctx.app).get(`/api/admin/questions?jobId=${jobId}&status=approved&pageSize=50`).set(auth(admin));
    const bulk = await request(ctx.app)
      .post('/api/admin/questions/bulk')
      .set(auth(admin))
      .send({ ids: approved.body.items.map((q: { id: string }) => q.id), action: 'publish' });
    expect(bulk.body.failed).toBe(0);
    expect(bulk.body.succeeded).toBe(20);
  });

  it('generates and publishes a mock test from published questions only', async () => {
    const res = await request(ctx.app)
      .post('/api/admin/mock-tests/generate')
      .set(auth(admin))
      .send({
        examId: ids.examId,
        title: 'UP Constable Percentage Mock 1',
        language: 'hi',
        totalQuestions: 10,
        durationMinutes: 12,
        marksPerQuestion: 2,
        negativeMarks: 0.5,
        difficulty: { easy: 30, medium: 50, hard: 20 },
        sections: [{ subjectId: ids.mathsId, count: 10 }],
      });
    expect(res.status).toBe(201);
    expect(res.body.report.sections[0].byDifficulty).toEqual({ easy: 3, medium: 5, hard: 2 });
    const qids = res.body.test.questions.map((q: { id: string }) => q.id);
    expect(new Set(qids).size).toBe(10);
    mockTestId = res.body.test.id;
    const pub = await request(ctx.app).post(`/api/admin/mock-tests/${mockTestId}/publish`).set(auth(admin));
    expect(pub.body.status).toBe('published');
  });

  it('serves the test to website users without the answer key', async () => {
    const list = await request(ctx.app).get('/api/mock-tests?state=up&examType=constable');
    expect(list.body.items.map((t: { id: string }) => t.id)).toContain(mockTestId);
    const test = await request(ctx.app).get(`/api/mock-tests/${mockTestId}`);
    expect(test.status).toBe(200);
    expect(test.body.durationMinutes).toBe(12);
    expect(test.body.questions).toHaveLength(10);
    expect(test.body.questions[0].options).toHaveLength(4);
    const body = JSON.stringify(test.body);
    expect(body).not.toContain('correctOption');
    expect(body).not.toContain('explanation');
  });

  it('scores a submission on the server and ignores client scores', async () => {
    const user = await userToken(ctx.app);
    const start = await request(ctx.app).post(`/api/mock-tests/${mockTestId}/start`).set(auth(user));
    expect(start.status).toBe(201);
    const key = await request(ctx.app).get(`/api/admin/mock-tests/${mockTestId}`).set(auth(admin));
    const questions = key.body.questions as { id: string; correctOption: string }[];
    // 6 right, 2 wrong, 2 blank.
    const answers = questions.map((q, i) => ({
      questionId: q.id,
      selectedOption: i < 6 ? q.correctOption : i < 8 ? 'ABCD'.replace(q.correctOption, '')[0] : null,
    }));
    const res = await request(ctx.app)
      .post(`/api/mock-tests/${mockTestId}/submit`)
      .set(auth(user))
      .send({ attemptId: start.body.attemptId, answers, score: 9999, correct: 10 });
    expect(res.status).toBe(200);
    expect(res.body.summary).toEqual({
      totalQuestions: 10,
      attempted: 8,
      correct: 6,
      incorrect: 2,
      unanswered: 2,
      score: 11, // 6 × 2 − 2 × 0.5
      maxScore: 20,
      percentage: 55,
    });
    expect(res.body.questions[0].correctOption).toMatch(/^[A-D]$/);
    expect(res.body.questions[0].explanation).toBeTruthy();

    // Analytics picks it up.
    const a = await request(ctx.app).get('/api/admin/analytics?minAttempts=1').set(auth(admin));
    expect(a.body.testsAttempted).toBe(1);
    expect(a.body.questionsAttempted).toBe(8);
    expect(a.body.averageScorePercentage).toBe(55);
    expect(a.body.mostAttemptedExams[0].name).toBe('UP Police Constable');
  });

  it('shows the pipeline on the dashboard', async () => {
    const d = await request(ctx.app).get('/api/admin/dashboard').set(auth(admin));
    expect(d.body.questions.published).toBe(20);
    expect(d.body.mockTests.published).toBe(1);
    expect(d.body.generationJobs.completed).toBe(1);
  });
});
