import type { Found, Subject } from "./types";

/**
 * Automatic candidate screening. These are deliberately conservative text and
 * metadata checks — an API calling something a "photo" is not taken as proof
 * that it is a real photograph of the right place — and every rejection keeps
 * its reason so the admin can see (and override) what was filtered out.
 */

export type RejectReason =
  | "MISSING_LICENSE"
  | "NON_FREE_LICENSE"
  | "LOW_RESOLUTION"
  | "NOT_A_PHOTO"
  | "AI_GENERATED"
  | "LOGO_OR_WATERMARK"
  | "STOCK_PLACEHOLDER"
  | "IRRELEVANT"
  | "WRONG_LOCATION"
  | "DUPLICATE"
  | "BROKEN_IMAGE"
  | "PROVIDER_REJECT";

export const REJECT_LABEL: Record<RejectReason, string> = {
  MISSING_LICENSE: "Licence or creator could not be identified",
  NON_FREE_LICENSE: "Licence does not permit use on the website",
  LOW_RESOLUTION: "Resolution too low",
  NOT_A_PHOTO: "Not a photograph (map, drawing, illustration, scan…)",
  AI_GENERATED: "AI-generated / digital art",
  LOGO_OR_WATERMARK: "Logo or watermark",
  STOCK_PLACEHOLDER: "Placeholder or template image",
  IRRELEVANT: "Does not show this place",
  WRONG_LOCATION: "Shows a different location",
  DUPLICATE: "Duplicate of another candidate",
  BROKEN_IMAGE: "Image URL does not load",
  PROVIDER_REJECT: "Rejected by provider metadata"
};

const STOP = new Set(["the", "of", "and", "a", "an", "at", "in", "on", "to", "sri", "shri", "shree", "new", "old", "great", "india", "indian"]);
/** Words that describe what a place is rather than which place it is. */
const GENERIC = new Set([
  "temple", "temples", "mandir", "fort", "palace", "museum", "lake", "valley", "ghat", "ghats", "garden", "gardens", "park", "national", "falls",
  "waterfall", "waterfalls", "beach", "church", "mosque", "masjid", "group", "monument", "monuments", "sanctuary", "wildlife", "hill", "hills",
  "river", "view", "point", "viewpoint", "market", "bazaar", "gate", "tomb", "cave", "caves", "dam", "bridge", "island", "pass", "peak", "glacier",
  "monastery", "gompa", "stupa", "shrine", "dargah", "gurudwara", "gurdwara", "memorial", "square", "road", "street", "city", "town", "village",
  "eastern", "western", "northern", "southern", "upper", "lower", "main", "central", "complex", "area", "site", "ruins", "station", "lakes"
]);

const NOT_PHOTO = /\b(maps?|plan|floor plan|diagram|flag|emblem|coat of arms|seal of|icon|chart|graph|drawing|painting|illustration|sketch|engraving|lithograph|watercolou?r|poster|postage stamp|stamp of|banknote|coin|screenshot|vector|clip ?art|cartoon|infographic|render|rendering|3d model|artwork|manuscript|miniature painting|blueprint|scan of|scanned|svg)\b/i;
const AI = /\b(ai[- ]generated|ai art|ai[- ]image|generative ai|generated by ai|midjourney|stable diffusion|dall[- ·]?e|digital art|concept art|fantasy art|neural)\b/i;
const LOGO = /\b(watermark(ed)?|logo|logotype|trademark)\b/i;
const PLACEHOLDER = /\b(placeholder|no image|image coming soon|sample image|template|mock-?up)\b/i;

export function norm(s: string): string {
  return s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
}

const words = (s: string) => norm(s).split(" ").filter((w) => w && !STOP.has(w));
const distinctive = (s: string) => words(s).filter((w) => !GENERIC.has(w) && w.length > 1);
const has = (text: string, word: string) => new RegExp(`(^| )${word}( |$)`).test(text);

/** Removes a parenthesised alias: "Vaishno Devi (Katra)" → "Vaishno Devi". */
export const cleanPlaceName = (s: string) => s.replace(/\s*\([^)]*\)\s*/g, " ").replace(/\s+/g, " ").trim();
export const aliasesOf = (s: string) => [...s.matchAll(/\(([^)]+)\)/g)].map((m) => m[1].trim()).filter(Boolean);

export function haversineKm(aLat: number, aLon: number, bLat: number, bLon: number): number {
  const R = 6371;
  const dLat = ((bLat - aLat) * Math.PI) / 180;
  const dLon = ((bLon - aLon) * Math.PI) / 180;
  const x = Math.sin(dLat / 2) ** 2 + Math.cos((aLat * Math.PI) / 180) * Math.cos((bLat * Math.PI) / 180) * Math.sin(dLon / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(x));
}

export interface Assessment {
  ok: boolean;
  reason: RejectReason | null;
  detail: string | null;
  score: number;
}

const reject = (reason: RejectReason, detail: string | null = null): Assessment => ({ ok: false, reason, detail, score: 0 });

/** Screens one candidate for one subject. `minLongEdge` comes from the settings. */
export function assess(f: Found, s: Subject, minLongEdge: number): Assessment {
  const img = f.image;
  if (f.hardReject) return reject(f.hardReject.startsWith("NON_FREE") ? "NON_FREE_LICENSE" : f.hardReject.startsWith("NOT_A_PHOTO") ? "NOT_A_PHOTO" : "PROVIDER_REJECT", f.hardReject.replace(/^[A-Z_]+:?\s*/, "") || null);
  if (!img.license || !img.source_page_url) return reject("MISSING_LICENSE");
  if (img.attribution_required && !img.photographer && !img.attribution_text) return reject("MISSING_LICENSE", "creator unknown but attribution is required");
  if (f.mime && !/^image\/(jpeg|webp)$/.test(f.mime)) return reject("NOT_A_PHOTO", f.mime.replace("image/", "").toUpperCase());

  const w = img.width ?? 0;
  const h = img.height ?? 0;
  if (!w || !h) return reject("LOW_RESOLUTION", "size unknown");
  if (Math.max(w, h) < minLongEdge || Math.min(w, h) < Math.round(minLongEdge / 2.5)) return reject("LOW_RESOLUTION", `${w}×${h}`);

  const text = norm(f.text);
  if (AI.test(text)) return reject("AI_GENERATED");
  if (NOT_PHOTO.test(text)) return reject("NOT_A_PHOTO", text.match(NOT_PHOTO)?.[0] ?? null);
  if (LOGO.test(text)) return reject("LOGO_OR_WATERMARK");
  if (PLACEHOLDER.test(text)) return reject("STOCK_PLACEHOLDER");

  // Location: coordinates first, then names.
  if (img.latitude != null && img.longitude != null && s.lat != null && s.lon != null) {
    const km = haversineKm(s.lat, s.lon, img.latitude, img.longitude);
    if (km > (s.kind === "attraction" ? 30 : 80)) return reject("WRONG_LOCATION", `${Math.round(km)} km away`);
  }

  const cityName = cleanPlaceName(s.city);
  const aTokens = distinctive(cleanPlaceName(s.name));
  const cTokens = [...new Set([...distinctive(cityName), ...s.cityAliases.flatMap(distinctive)])];
  const sTokens = s.state ? distinctive(s.state) : [];
  const aAll = aTokens.length > 0 && aTokens.every((t) => has(text, t));
  const aAny = aTokens.some((t) => has(text, t));
  const cityHit = cTokens.some((t) => has(text, t));
  const stateHit = sTokens.length > 0 && sTokens.every((t) => has(text, t));
  const near = f.distance_m != null;
  const phrase = norm(cleanPlaceName(s.name));
  const phraseHit = phrase.length > 3 && text.includes(phrase);

  const mentionsOther = s.otherPlaces.find((p) => {
    const n = norm(cleanPlaceName(p));
    return n.length >= 4 && n !== norm(cityName) && !norm(cityName).includes(n) && !phrase.includes(n) && has(text, n.replace(/ /g, " "));
  });

  if (s.kind === "attraction") {
    const relevant = (aAll && (aTokens.length >= 2 || cityHit || stateHit || near)) || (aAny && cityHit) || (near && (aAny || cityHit)) || (phraseHit && aTokens.length === 0 && cityHit);
    if (!relevant) {
      if (mentionsOther) return reject("WRONG_LOCATION", mentionsOther);
      return reject("IRRELEVANT");
    }
  } else if (!(cityHit || near)) {
    return mentionsOther ? reject("WRONG_LOCATION", mentionsOther) : reject("IRRELEVANT");
  }
  if (mentionsOther && !aAny && !cityHit) return reject("WRONG_LOCATION", mentionsOther);

  let score = 0;
  if (aAll) score += 6;
  else if (aAny) score += 3;
  if (phraseHit) score += 3;
  if (cityHit) score += 2;
  if (stateHit) score += 1;
  if (near) score += Math.max(0, 4 - (f.distance_m ?? 0) / 250);
  if (f.quality_mark) score += 2;
  if (img.provider === "wikimedia") score += 1;
  const long = Math.max(w, h);
  if (long >= 3000) score += 1.5;
  else if (long >= 2000) score += 1;
  if (w > h) score += 0.5;
  return { ok: true, reason: null, detail: null, score: Math.round(score * 10) / 10 };
}

/**
 * Keys that identify the same picture: the provider's own id, and the file URL (the same file reached
 * through a different query or listing). Titles and camera sizes are deliberately not used — a series
 * of photos by one photographer ("Temple 01", "Temple 02", all 6000×4000) are different pictures.
 */
export function dedupeKeys(f: Found): string[] {
  const img = f.image;
  const keys = [`${img.provider}:${img.provider_image_id ?? img.id}`];
  if (img.original_url) keys.push(`url:${img.original_url.split("?")[0]}`);
  return keys;
}
