"""add voice_mode to voice_profiles

Revision ID: 086d4b53e4ad
Revises: 464acdcd09b9
Create Date: 2026-09-24 05:09:14.531924
"""
from alembic import op
import sqlalchemy as sa


revision = '086d4b53e4ad'
down_revision = '464acdcd09b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_profiles', sa.Column('voice_mode', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_profiles', 'voice_mode')
    # ### end Alembic commands ###
