"""initial schema

Revision ID: 464acdcd09b9
Revises: 
Create Date: 2026-09-22 14:30:15.388592
"""
from alembic import op
import sqlalchemy as sa


revision = '464acdcd09b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_jobs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_lessons', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_jobs_owner_id'), 'batch_jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_batch_jobs_status'), 'batch_jobs', ['status'], unique=False)
    op.create_table('deletion_events',
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('deletion_reason', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_events_owner_id'), 'deletion_events', ['owner_id'], unique=False)
    op.create_table('deletion_jobs',
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('processed_items', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('result_path', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deletion_jobs_owner_id'), 'deletion_jobs', ['owner_id'], unique=False)
    op.create_table('lessons',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_filename', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('source_file_asset_id', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('education_level', sa.String(), nullable=False),
    sa.Column('teaching_style', sa.String(), nullable=False),
    sa.Column('video_format', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('change_examples', sa.Boolean(), nullable=False),
    sa.Column('change_numbers', sa.Boolean(), nullable=False),
    sa.Column('change_context', sa.Boolean(), nullable=False),
    sa.Column('preserve_difficulty', sa.Boolean(), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_owner_id'), 'lessons', ['owner_id'], unique=False)
    op.create_index(op.f('ix_lessons_source_hash'), 'lessons', ['source_hash'], unique=False)
    op.create_index(op.f('ix_lessons_status'), 'lessons', ['status'], unique=False)
    op.create_table('project_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'key', name='uq_project_setting_owner_key')
    )
    op.create_index(op.f('ix_project_settings_owner_id'), 'project_settings', ['owner_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('api_token', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_token'), 'users', ['api_token'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('voice_profiles',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('style', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_profiles_owner_id'), 'voice_profiles', ['owner_id'], unique=False)
    op.create_table('batch_items',
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch_jobs.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_items_batch_id'), 'batch_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_batch_items_lesson_id'), 'batch_items', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_batch_items_owner_id'), 'batch_items', ['owner_id'], unique=False)
    op.create_index(op.f('ix_batch_items_status'), 'batch_items', ['status'], unique=False)
    op.create_table('examples',
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('original_example', sa.JSON(), nullable=False),
    sa.Column('generated_example', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_detail', sa.JSON(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examples_lesson_id'), 'examples', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_examples_owner_id'), 'examples', ['owner_id'], unique=False)
    op.create_table('lesson_analyses',
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('analysis_json', sa.JSON(), nullable=False),
    sa.Column('source_hash', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_analyses_lesson_id'), 'lesson_analyses', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_analyses_owner_id'), 'lesson_analyses', ['owner_id'], unique=False)
    op.create_table('quality_reports',
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('video_asset_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_reports_lesson_id'), 'quality_reports', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_quality_reports_owner_id'), 'quality_reports', ['owner_id'], unique=False)
    op.create_table('render_jobs',
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('logs', sa.Text(), nullable=False),
    sa.Column('video_asset_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_jobs_lesson_id'), 'render_jobs', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_render_jobs_owner_id'), 'render_jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_render_jobs_status'), 'render_jobs', ['status'], unique=False)
    op.create_table('teaching_plans',
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=False),
    sa.Column('script_hash', sa.String(), nullable=False),
    sa.Column('prompt_version', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_plans_lesson_id'), 'teaching_plans', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_teaching_plans_owner_id'), 'teaching_plans', ['owner_id'], unique=False)
    op.create_index(op.f('ix_teaching_plans_script_hash'), 'teaching_plans', ['script_hash'], unique=False)
    op.create_table('video_assets',
    sa.Column('lesson_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('thumbnail_path', sa.String(), nullable=False),
    sa.Column('subtitle_srt_path', sa.String(), nullable=False),
    sa.Column('subtitle_vtt_path', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('render_hash', sa.String(), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_assets_lesson_id'), 'video_assets', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_video_assets_owner_id'), 'video_assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_video_assets_render_hash'), 'video_assets', ['render_hash'], unique=False)
    op.create_table('scenes',
    sa.Column('teaching_plan_id', sa.String(), nullable=False),
    sa.Column('scene_key', sa.String(length=64), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('scene_json', sa.JSON(), nullable=False),
    sa.Column('narration_text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['teaching_plan_id'], ['teaching_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenes_owner_id'), 'scenes', ['owner_id'], unique=False)
    op.create_index(op.f('ix_scenes_teaching_plan_id'), 'scenes', ['teaching_plan_id'], unique=False)
    op.create_index(op.f('ix_scenes_text_hash'), 'scenes', ['text_hash'], unique=False)
    op.create_table('audio_assets',
    sa.Column('scene_id', sa.String(), nullable=False),
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('text_hash', sa.String(), nullable=False),
    sa.Column('audio_path', sa.String(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_assets_owner_id'), 'audio_assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_audio_assets_scene_id'), 'audio_assets', ['scene_id'], unique=False)
    op.create_index(op.f('ix_audio_assets_text_hash'), 'audio_assets', ['text_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_assets_text_hash'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_scene_id'), table_name='audio_assets')
    op.drop_index(op.f('ix_audio_assets_owner_id'), table_name='audio_assets')
    op.drop_table('audio_assets')
    op.drop_index(op.f('ix_scenes_text_hash'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_teaching_plan_id'), table_name='scenes')
    op.drop_index(op.f('ix_scenes_owner_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_video_assets_render_hash'), table_name='video_assets')
    op.drop_index(op.f('ix_video_assets_owner_id'), table_name='video_assets')
    op.drop_index(op.f('ix_video_assets_lesson_id'), table_name='video_assets')
    op.drop_table('video_assets')
    op.drop_index(op.f('ix_teaching_plans_script_hash'), table_name='teaching_plans')
    op.drop_index(op.f('ix_teaching_plans_owner_id'), table_name='teaching_plans')
    op.drop_index(op.f('ix_teaching_plans_lesson_id'), table_name='teaching_plans')
    op.drop_table('teaching_plans')
    op.drop_index(op.f('ix_render_jobs_status'), table_name='render_jobs')
    op.drop_index(op.f('ix_render_jobs_owner_id'), table_name='render_jobs')
    op.drop_index(op.f('ix_render_jobs_lesson_id'), table_name='render_jobs')
    op.drop_table('render_jobs')
    op.drop_index(op.f('ix_quality_reports_owner_id'), table_name='quality_reports')
    op.drop_index(op.f('ix_quality_reports_lesson_id'), table_name='quality_reports')
    op.drop_table('quality_reports')
    op.drop_index(op.f('ix_lesson_analyses_owner_id'), table_name='lesson_analyses')
    op.drop_index(op.f('ix_lesson_analyses_lesson_id'), table_name='lesson_analyses')
    op.drop_table('lesson_analyses')
    op.drop_index(op.f('ix_examples_owner_id'), table_name='examples')
    op.drop_index(op.f('ix_examples_lesson_id'), table_name='examples')
    op.drop_table('examples')
    op.drop_index(op.f('ix_batch_items_status'), table_name='batch_items')
    op.drop_index(op.f('ix_batch_items_owner_id'), table_name='batch_items')
    op.drop_index(op.f('ix_batch_items_lesson_id'), table_name='batch_items')
    op.drop_index(op.f('ix_batch_items_batch_id'), table_name='batch_items')
    op.drop_table('batch_items')
    op.drop_index(op.f('ix_voice_profiles_owner_id'), table_name='voice_profiles')
    op.drop_table('voice_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_token'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_project_settings_owner_id'), table_name='project_settings')
    op.drop_table('project_settings')
    op.drop_index(op.f('ix_lessons_status'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_source_hash'), table_name='lessons')
    op.drop_index(op.f('ix_lessons_owner_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_deletion_jobs_owner_id'), table_name='deletion_jobs')
    op.drop_table('deletion_jobs')
    op.drop_index(op.f('ix_deletion_events_owner_id'), table_name='deletion_events')
    op.drop_table('deletion_events')
    op.drop_index(op.f('ix_batch_jobs_status'), table_name='batch_jobs')
    op.drop_index(op.f('ix_batch_jobs_owner_id'), table_name='batch_jobs')
    op.drop_table('batch_jobs')
    # ### end Alembic commands ###
