import { Config } from "@remotion/cli/config";
import fs from "node:fs";
import path from "node:path";

Config.setVideoImageFormat("jpeg");

// Audio (and any other) assets generated by the backend live under
// STORAGE_PATH (default <repo_root>/storage) and are referenced from
// Teaching Plan props as paths relative to that root, e.g.
// "audio/scene_001_ab12.wav". Pointing Remotion's public dir there lets
// the composition load them via `staticFile()` without copying files
// into the renderer project (see docs/VIDEO_RENDERING.md).
const storagePath = process.env.STORAGE_PATH || path.resolve(__dirname, "..", "storage");
Config.setPublicDir(storagePath);
Config.setOverwriteOutput(true);
Config.setChromiumOpenGlRenderer("angle");

// Use a pre-installed headless Chrome shell instead of letting Remotion
// download its own binary, for environments where outbound access to
// remotion.media/googlechromelabs is restricted. Set
// REMOTION_BROWSER_EXECUTABLE to override.
const candidatePaths = [
  process.env.REMOTION_BROWSER_EXECUTABLE,
  "/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell",
  "/opt/pw-browsers/chromium-1194/chrome-linux/chrome",
].filter((p): p is string => Boolean(p));

const browserExecutable = candidatePaths.find((p) => fs.existsSync(p));
if (browserExecutable) {
  Config.setBrowserExecutable(browserExecutable);
}
