#!/usr/bin/env node
// Validates the FOCUS Plant Library on disk and regenerates the app's static
// image map (src/plants/plantImages.ts). Runs in CI: a missing, duplicate,
// non-square or odd-sized file fails the build.
//
//   node scripts/checkPlantLibrary.mjs            # check + write plantImages.ts
//   node scripts/checkPlantLibrary.mjs --check    # check only, no writes (CI)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { LIBRARY_DIR, MANIFEST_PATH } from './plantLibrary/writeManifest.mjs';
import { manifestRows } from './plantLibrary/species.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const MODULE_PATH = path.resolve(here, '..', 'src', 'plants', 'plantImages.ts');
const checkOnly = process.argv.includes('--check');

function pngSize(buf) {
  if (buf.length < 24 || buf.toString('ascii', 1, 4) !== 'PNG') return null;
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

const problems = [];
const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));
const expected = manifestRows();

if (manifest.plants.length !== 100) problems.push(`manifest has ${manifest.plants.length} plants, expected 100`);
expected.forEach((row, i) => {
  const p = manifest.plants[i];
  if (!p) return;
  for (const key of ['id', 'name', 'filename', 'category', 'growthForm', 'rootType']) {
    if (p[key] !== row[key]) problems.push(`manifest #${row.id} ${key} is "${p[key]}", species.mjs says "${row[key]}" — run npm run plants:manifest`);
  }
});

const sizes = new Map();
const seenNames = new Set();
const seenFiles = new Set();
for (const p of manifest.plants) {
  if (seenNames.has(p.name)) problems.push(`duplicate name ${p.name}`);
  if (seenFiles.has(p.filename)) problems.push(`duplicate filename ${p.filename}`);
  seenNames.add(p.name);
  seenFiles.add(p.filename);
  if (!/^\d{3}_[a-z0-9_]+\.png$/.test(p.filename)) problems.push(`bad filename ${p.filename}`);
  const file = path.join(LIBRARY_DIR, p.filename);
  if (!fs.existsSync(file)) {
    problems.push(`missing file ${p.filename}`);
    continue;
  }
  const s = pngSize(fs.readFileSync(file));
  if (!s) problems.push(`${p.filename} is not a PNG`);
  else if (s.width !== s.height) problems.push(`${p.filename} is not square (${s.width}×${s.height})`);
  else sizes.set(`${s.width}`, (sizes.get(`${s.width}`) ?? 0) + 1);
}
if (sizes.size > 1) problems.push(`mixed sizes: ${[...sizes].map(([k, v]) => `${k}px×${v}`).join(', ')}`);
const stray = fs
  .readdirSync(LIBRARY_DIR)
  .filter((f) => f.endsWith('.png') && !seenFiles.has(f) && !f.includes('.rejected'));
if (stray.length) problems.push(`files not in manifest: ${stray.join(', ')}`);

const placeholders = manifest.plants.filter((p) => p.placeholder !== false).length;
console.log(`plant library: ${manifest.plants.length} plants, ${manifest.plants.length - placeholders} generated, ${placeholders} placeholders, sizes ${[...sizes.keys()].join('/') || 'n/a'}px`);

if (problems.length) {
  console.error('plant library problems:\n' + problems.map((p) => `  • ${p}`).join('\n'));
  process.exit(1);
}

if (!checkOnly) {
  const lines = [
    '// GENERATED by scripts/checkPlantLibrary.mjs — do not edit.',
    '// Metro needs a literal require() per asset, so the 100 plant images are',
    '// listed here once; plantLibrary.ts looks them up by id.',
    '/* eslint-disable */',
    'export const PLANT_IMAGES: Record<number, number> = {',
    ...manifest.plants.map((p) => `  ${p.id}: require('../../assets/plants/FOCUS_PLANT_LIBRARY/${p.filename}'),`),
    '};',
    '',
  ];
  const next = lines.join('\n');
  const current = fs.existsSync(MODULE_PATH) ? fs.readFileSync(MODULE_PATH, 'utf8') : '';
  if (current !== next) {
    fs.mkdirSync(path.dirname(MODULE_PATH), { recursive: true });
    fs.writeFileSync(MODULE_PATH, next);
    console.log(`wrote ${path.relative(process.cwd(), MODULE_PATH)}`);
  }
}
