"""Turn assets/paradise/sprites.json into src/paradise/sprites.generated.ts:
the species' eight stage sprites (and 256-px thumbnails) with their sizes
and pivots, plus the require() table Metro needs.

    python gen_paradise_pack.py
"""
import json, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
pack = ROOT / "assets" / "paradise"
out = ROOT / "src" / "paradise" / "sprites.generated.ts"

m = json.loads((pack / "sprites.json").read_text()) if (pack / "sprites.json").exists() else {"species": {}, "stages": []}
species = {}
files = set()
for sid, rec in m.get("species", {}).items():
    stages = []
    for st in rec.get("stages") or []:
        if st and (pack / st["file"]).exists():
            stages.append({k: st[k] for k in ("file", "thumb", "px", "widthM", "heightM", "pivot", "boxM") if k in st} | ({"sway": st["sway"]} if st.get("sway") else {}))
            files.add(st["file"])
            if st.get("thumb") and (pack / st["thumb"]).exists():
                files.add(st["thumb"])
        else:
            stages.append(None)
    if any(stages):
        species[sid] = {"segment": rec["segment"], "stages": stages}

# garden extras (the pond plinth) drawn with the plants
extras = json.loads((pack / "extras.json").read_text()) if (pack / "extras.json").exists() else {}
extras = {k: {kk: v[kk] for kk in ("file", "thumb", "px", "widthM", "heightM", "pivot", "boxM") if kk in v} for k, v in extras.items() if (pack / v["file"]).exists()}
for v in extras.values():
    files.add(v["file"])

total = sum((pack / f).stat().st_size for f in files)
lines = [
    "// GENERATED by tools/balcony-render/gen_paradise_pack.py — do not edit by hand.",
    "// Re-render the species (render_paradise.py) to change it.",
    "/* eslint-disable */",
    "import type { SpeciesSprites, Sprite } from './types';",
    "",
    f"export const PARADISE_SPRITES: Record<string, SpeciesSprites> = {json.dumps(species, separators=(',', ':'))} as unknown as Record<string, SpeciesSprites>;",
    "",
    f"export const PARADISE_EXTRAS: Record<string, Sprite> = {json.dumps(extras, separators=(',', ':'))} as unknown as Record<string, Sprite>;",
    "",
    "export const PARADISE_IMAGES: Record<string, number> = {",
]
for f in sorted(files):
    lines.append(f'  "{f}": require("../../assets/paradise/{f}"),')
lines.append("};")
lines.append("")
out.write_text("\n".join(lines))
print(f"paradise: {len(species)} species, {len(files)} images, {total / 1e6:.1f} MB → {out}")
