"""Turn assets/garden3d/sprites.json + textures.json into the app module
src/garden/sprites.generated.ts: the sprite manifest, the image requires
and the store entries of the new plants.

    python gen_sprites_pack.py [assets/garden3d] [src/garden/sprites.generated.ts]
"""
import json, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
import bpy  # noqa: F401  (bmesh is only importable after bpy)
from focusbalcony import garden_plants_extra as extra

ROOT = pathlib.Path(__file__).resolve().parents[2]
pack = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "assets" / "garden3d"
out = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "src" / "garden" / "sprites.generated.ts"

m = json.loads((pack / "sprites.json").read_text())
tex = json.loads((pack / "textures.json").read_text()) if (pack / "textures.json").exists() else {}


def files_in(obj, acc):
    if isinstance(obj, dict):
        if "file" in obj and isinstance(obj["file"], str):
            acc.add(obj["file"])
        for v in obj.values():
            files_in(v, acc)
    elif isinstance(obj, list):
        for v in obj:
            files_in(v, acc)


files = set()
files_in(m, files)
files_in(tex, files)
files = sorted(f for f in files if (pack / f).exists())
rel = pathlib.Path("..") / ".." / pack.relative_to(ROOT)

store = {k: {"name": v[0], "category": v[1], "blurb": v[2], "coins": v[3], "unlockMinutes": v[4], "growable": k in extra.GROWABLE_EXTRA} for k, v in extra.META.items()}

lines = [
    "// GENERATED by tools/balcony-render/gen_sprites_pack.py — do not edit by hand.",
    "// Re-render the sprites (tools/balcony-render/README.md) to change it.",
    "/* eslint-disable */",
    "import type { SpriteManifest, TextureManifest } from './types';",
    "",
    f"export const SPRITES: SpriteManifest = {json.dumps(m, separators=(',', ':'))} as unknown as SpriteManifest;",
    "",
    f"export const TEXTURES: TextureManifest = {json.dumps(tex, separators=(',', ':'))} as unknown as TextureManifest;",
    "",
    f"export const EXTRA_STORE = {json.dumps(store, separators=(',', ':'))} as const;",
    "",
    "export const SPRITE_IMAGES: Record<string, number> = {",
]
for f in files:
    lines.append(f'  "{f}": require("{(rel / f).as_posix()}"),')
lines.append("};")
lines.append("")
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("\n".join(lines))
total = sum((pack / f).stat().st_size for f in files)
print(f"garden3d: {len(m.get('items', {}))} items, {len(files)} images, {total / 1e6:.1f} MB → {out}")
