import { AssetDefinition } from '../state/types';

/** The bundled starter catalog (architecture doc, section H/K). Every entry
 * here is a PLACEHOLDER built from primitives; swapping one for real art is
 * `kind: 'glb', ref: '<uri>', placeholder: false` — nothing else changes.
 * A remote catalog served by the API merges over this map later. */
export const ASSET_CATALOG: Record<string, AssetDefinition> = {
  sofa_sectional_white_01: {
    id: 'sofa_sectional_white_01',
    price: { coins: 240 },
    name: 'White sectional sofa',
    category: 'FURNITURE',
    kind: 'procedural',
    ref: 'sofa_sectional_white',
    placementType: 'floor',
    footprint: [2.22, 0.92, 0.95],
    scaleLimits: [1, 1],
    rotationAllowed: true,
    placeholder: true,
  },
  table_coffee_low_01: {
    id: 'table_coffee_low_01',
    price: { coins: 90 },
    name: 'Low walnut coffee table',
    category: 'TABLES',
    kind: 'procedural',
    ref: 'table_coffee_low',
    placementType: 'floor',
    footprint: [1.1, 0.6, 0.4],
    scaleLimits: [0.85, 1.15],
    rotationAllowed: true,
    placeholder: true,
  },
  planter_trough_hedge_01: {
    id: 'planter_trough_hedge_01',
    price: { coins: 60 },
    growable: true,
    name: 'Hedge trough planter',
    category: 'PLANTS',
    kind: 'procedural',
    ref: 'planter_trough_hedge',
    placementType: 'floor',
    footprint: [1.62, 0.5, 1.1],
    scaleLimits: [0.8, 1.2],
    rotationAllowed: true,
    placeholder: true,
  },
  planter_tall_broadleaf_01: {
    id: 'planter_tall_broadleaf_01',
    price: { coins: 80 },
    growable: true,
    unlockMinutes: 45,
    name: 'Tall broad-leaf plant',
    category: 'PLANTS',
    kind: 'procedural',
    ref: 'planter_tall_broadleaf',
    placementType: 'floor',
    footprint: [0.8, 0.8, 1.75],
    scaleLimits: [0.8, 1.3],
    rotationAllowed: true,
    placeholder: true,
  },
  lamp_floor_arc_01: {
    id: 'lamp_floor_arc_01',
    price: { coins: 120 },
    unlockMinutes: 90,
    name: 'Arc floor lamp',
    category: 'LIGHTING',
    kind: 'procedural',
    ref: 'lamp_floor_arc',
    placementType: 'floor',
    footprint: [0.4, 0.7, 1.9],
    scaleLimits: [1, 1],
    rotationAllowed: true,
    placeholder: true,
  },
  lantern_black_01: {
    id: 'lantern_black_01',
    price: { coins: 35 },
    unlockMinutes: 10,
    name: 'Candle lantern',
    category: 'DECOR',
    kind: 'procedural',
    ref: 'lantern_black',
    placementType: 'floor',
    footprint: [0.3, 0.3, 0.55],
    scaleLimits: [0.8, 1.4],
    rotationAllowed: true,
    placeholder: true,
  },
  rug_outdoor_01: {
    id: 'rug_outdoor_01',
    price: { coins: 70 },
    unlockMinutes: 180,
    name: 'Outdoor rug',
    category: 'RUGS',
    kind: 'procedural',
    ref: 'rug_outdoor',
    placementType: 'floor',
    footprint: [2.2, 1.6, 0.02],
    scaleLimits: [0.8, 1.2],
    rotationAllowed: true,
    placeholder: true,
  },
};

export function getAsset(id: string): AssetDefinition | undefined {
  return ASSET_CATALOG[id];
}
